### PR TITLE
Added datasets split per language for glossing

### PR DESCRIPTION
**Pull request by LEK85**

### CODE REVIEW

**Comment by Bibiko** [comment]
I would suggest leaving these files in the `glossing` branch and editing them there. Once it's done, make a file out of them. This file can then live on main branch in /etc.

**Comment by LEK85** [comment]
I agree. We will.

**Comment by LEK85** [comment]
Hi, @Bibiko , hadn't we said we would keep the glossed data in the separate branch `glossing` rather than merging it with `main`?

**Comment by Bibiko** [comment]
Yes - but since the glossed data will be part of the main repo we decided to go with the main branch for versioning. Branches can be deleted and then we would loose the information about who did what when.

**Comment by LEK85** [comment]
OK. At this stage, we'll keep updating the glossed data, and I'm working in some scripts for sanity check them based on the glossing rules we defined. I'll keep all in the `etc/glossed` folder

**Pull request merged**
